"""iteracion 2 fusion de leads y envio de cotizacion

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-21 03:04:23.353593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_leads_merged_into_id_leads', 'leads', ['merged_into_id'], ['id'])

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_merged_into_id_leads', type_='foreignkey')
        batch_op.drop_column('merged_into_id')

    # ### end Alembic commands ###
