"""iteracion 3 bitacora total encadenada

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-21 03:33:46.161476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actor_email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('actor_role', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False, server_default='negocio'))
        batch_op.add_column(sa.Column('summary', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prev_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_role'), ['actor_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_seq'), ['seq'], unique=True)

    # ### end Alembic commands ###
    _backfill_chain()


def _backfill_chain() -> None:
    """Numera y encadena los eventos que existían antes de esta migración (orden cronológico)."""
    from types import SimpleNamespace
    from app.audit import GENESIS, compute_hash
    bind = op.get_bind()
    cols = ["id", "at", "actor_id", "actor_email", "actor_role", "category", "action", "entity_type", "entity_id",
            "summary", "before", "after", "ip", "method", "path", "status", "request_id"]
    rows = bind.execute(sa.text(f"SELECT {', '.join(cols)} FROM audit_events ORDER BY at, id")).mappings().all()
    prev = GENESIS
    for n, r in enumerate(rows, start=1):
        data = dict(r)
        for k in ("before", "after"):
            if isinstance(data[k], str):
                import json
                data[k] = json.loads(data[k])
        if isinstance(data["at"], str):
            from datetime import datetime
            data["at"] = datetime.fromisoformat(data["at"])
        ev = SimpleNamespace(**data, seq=n, prev_hash=prev)
        h = compute_hash(ev)
        bind.execute(sa.text("UPDATE audit_events SET seq=:s, prev_hash=:p, hash=:h WHERE id=:i"),
                     {"s": n, "p": prev, "h": h, "i": data["id"]})
        prev = h



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_seq'))
        batch_op.drop_index(batch_op.f('ix_audit_events_category'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_role'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.alter_column('action',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.drop_column('hash')
        batch_op.drop_column('prev_hash')
        batch_op.drop_column('status')
        batch_op.drop_column('path')
        batch_op.drop_column('method')
        batch_op.drop_column('ip')
        batch_op.drop_column('summary')
        batch_op.drop_column('category')
        batch_op.drop_column('actor_role')
        batch_op.drop_column('actor_email')
        batch_op.drop_column('seq')

    # ### end Alembic commands ###
