"""operacion interna: inventario ventas compras rrhh caja mantenimiento avisos

Revision ID: 5a4be6059f62
Revises: 0003
Create Date: 2026-09-23 19:49:05.355145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('area', sa.String(length=60), nullable=True),
    sa.Column('duties', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_kind'), ['kind'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_no', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('area', sa.String(length=60), nullable=True),
    sa.Column('job_profile_id', sa.String(length=36), nullable=True),
    sa.Column('position_text', sa.String(length=160), nullable=True),
    sa.Column('hired_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_profile_id'], ['job_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('expires_on', sa.DateTime(), nullable=True),
    sa.Column('received_on', sa.DateTime(), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'code')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_expires_on'), ['expires_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_product_id'), ['product_id'], unique=False)

    op.create_table('notification_mutes',
    sa.Column('mute_key', sa.String(length=160), nullable=False),
    sa.Column('until', sa.DateTime(), nullable=True),
    sa.Column('muted_by', sa.String(length=36), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['muted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('mute_key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('target_role', sa.String(length=30), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('mute_key', sa.String(length=160), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_by', sa.String(length=36), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['read_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_mute_key'), ['mute_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_target_role'), ['target_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('petty_cash_funds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fund_amount_mxn', sa.Float(), nullable=False),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expected_date', sa.DateTime(), nullable=True),
    sa.Column('authorized_by', sa.String(length=36), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('supplier_invoice', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('identifier', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_employee_id', sa.String(length=36), nullable=True),
    sa.Column('purchased_on', sa.DateTime(), nullable=True),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('hours_used', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_type'), ['type'], unique=False)

    op.create_table('employment_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('start_on', sa.DateTime(), nullable=False),
    sa.Column('end_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employment_contracts_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employment_contracts_end_on'), ['end_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_employment_contracts_status'), ['status'], unique=False)

    op.create_table('petty_cash_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fund_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('amount_mxn', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('receipt_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['petty_cash_funds.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['attachments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petty_cash_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petty_cash_entries_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_entries_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_entries_type'), ['type'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('unit_cost_mxn', sa.Float(), nullable=True),
    sa.Column('received_kg', sa.Float(), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_items_product_id'), ['product_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('ref_type', sa.String(length=30), nullable=True),
    sa.Column('ref_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('maintenance_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('freq_days', sa.Integer(), nullable=True),
    sa.Column('freq_km', sa.Float(), nullable=True),
    sa.Column('freq_hours', sa.Float(), nullable=True),
    sa.Column('last_done_on', sa.DateTime(), nullable=True),
    sa.Column('last_done_km', sa.Float(), nullable=True),
    sa.Column('last_done_hours', sa.Float(), nullable=True),
    sa.Column('next_due_on', sa.DateTime(), nullable=True),
    sa.Column('next_due_km', sa.Float(), nullable=True),
    sa.Column('next_due_hours', sa.Float(), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plans_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plans_next_due_on'), ['next_due_on'], unique=False)

    op.create_table('sales_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('warehouse_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promised_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('invoice_folio', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_status'), ['status'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_name', sa.String(length=160), nullable=True),
    sa.Column('cost_mxn', sa.Float(), nullable=True),
    sa.Column('done_on', sa.DateTime(), nullable=True),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('hours_used', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['maintenance_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)

    op.create_table('sales_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('lot_id', sa.String(length=36), nullable=True),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('unit_price_mxn', sa.Float(), nullable=True),
    sa.Column('packaging', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_items_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('kg_per_unit', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('packaging', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('min_stock_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shelf_life_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('shelf_life_days')
        batch_op.drop_column('min_stock_kg')
        batch_op.drop_column('packaging')
        batch_op.drop_column('kg_per_unit')
        batch_op.drop_column('unit')

    with op.batch_alter_table('sales_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_items_order_id'))

    op.drop_table('sales_order_items')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_asset_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_status'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_account_id'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_next_due_on'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_asset_id'))

    op.drop_table('maintenance_plans')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_type'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_ref_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_lot_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_at'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('petty_cash_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petty_cash_entries_type'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_entries_fund_id'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_entries_category'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_entries_at'))

    op.drop_table('petty_cash_entries')
    with op.batch_alter_table('employment_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employment_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_employment_contracts_end_on'))
        batch_op.drop_index(batch_op.f('ix_employment_contracts_employee_id'))

    op.drop_table('employment_contracts')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_type'))
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))

    op.drop_table('assets')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_status'))

    op.drop_table('purchase_orders')
    op.drop_table('petty_cash_funds')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_target_role'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_mute_key'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_entity_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('notification_mutes')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_product_id'))
        batch_op.drop_index(batch_op.f('ix_lots_expires_on'))
        batch_op.drop_index(batch_op.f('ix_lots_code'))

    op.drop_table('lots')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_full_name'))
        batch_op.drop_index(batch_op.f('ix_employees_area'))

    op.drop_table('employees')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_kind'))
        batch_op.drop_index(batch_op.f('ix_attachments_expires_on'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_entity_id'))

    op.drop_table('attachments')
    op.drop_table('warehouses')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))

    op.drop_table('suppliers')
    op.drop_table('job_profiles')
    # ### end Alembic commands ###
